In [1]:
import numpy as np

In [2]:
# np.zeros(10)
# np.ones(10)
# np.full(5, 100)
# np.array([1, 2, 3, 4, 5])
# np.arange(1, 20)
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
    ])

In [5]:
# a[4]
# a[:, 2]
# a[1,3]

a[:, 4] = [10, 20, 30, 40, 50]
a[:]

array([[ 1,  2,  3,  4, 10],
       [ 6,  7,  8,  9, 20],
       [11, 12, 13, 14, 30],
       [16, 17, 18, 19, 40],
       [21, 22, 23, 24, 50]])

In [6]:
a = np.array([1,2,3,4])

b = np.array([2,0,5,1])

In [7]:
a[a > b]

array([2, 4])

In [8]:
a > b

array([False,  True, False,  True])

## Summarizing Operations

In [9]:
# Returns number

a.min()

np.int64(1)

In [10]:
a.max()

np.int64(4)

In [11]:
np.random.seed(42)

## Linear Algebra Operations

In [12]:
v1 = np.array([1,2,3])
v2 = np.array([2,0,5])

M1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
M2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

### Vector - Vector multiplication

In [13]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0] # Rows
    ans = 0.0

    for i in range(n):
        ans += u[i] * v[i]
    
    return ans


### Matrix - Vector multiplication

In [14]:
def matrix_vector_multiplication(U, v):

    assert U.shape[1] == v.shape[0]

    n = U.shape[0] # rows

    ans = np.zeros(U.shape[0])

    for i in range(n):
        ans[i] += vector_vector_multiplication(U[i,:], v)
    
    return ans


In [15]:
matrix_vector_multiplication(M1, v1)

array([14., 32., 50.])

### Matrix - Matrix multiplication

In [16]:
def matrix_matrix_multiplication(U, V):

    assert U.shape[1] == V.shape[0]

    n = U.shape[0] # rows
    m = V.shape[1] # cols

    ans = np.zeros([n, m])
    
    # for i in range(n):
    #     for j in range(m):
    #         ans[i, j] += vector_vector_multiplication(U[i,:], V[:,j])

    # Most optimal way
    for j in range(m):
        ans[:, j] = matrix_vector_multiplication(U, V[:, j])
    
    return ans

In [17]:
# matrix_matrix_multiplication(M1, M2)

# 2x3
M3 = np.array([
    [0, 0, 3],
    [1, 2, 0]
    ])

# 3x2
M4 = np.array([
    [1, 0],
    [1, 1],
    [0, 3]
])

# should bring
# 0 9
# 3 2

matrix_matrix_multiplication(M3, M4)



array([[0., 9.],
       [3., 2.]])

In [18]:
ans


NameError: name 'ans' is not defined

In [ ]:
I = np.eye(3)
I