In [1]:
import pandas as pd

### Q1. Pandas version

In [2]:
pd.__version__

'2.3.1'

In [3]:
# Getting the Data:

!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-28 15:07:35--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.1’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.008s  

2025-09-28 15:07:35 (101 MB/s) - ‘car_fuel_efficiency.csv.1’ saved [874188/874188]



In [4]:
df = pd.read_csv('./car_fuel_efficiency.csv')

In [5]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Q2. Records count

In [6]:
len(df)

9704

### Q3. Fuel types

In [7]:
df["fuel_type"].nunique()

2

### Q4. Missing values

In [8]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [9]:
# Answer: 4 columns contain nulls

### Q5. Max fuel efficiency

In [10]:
df[
    df['origin'] == 'Asia'
].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

In [11]:
# Answer: 23.759122836520497

### Q6. Median value of horsepower

In [13]:
df['horsepower'].median()

np.float64(149.0)

In [14]:
df.horsepower.isnull().sum()

np.int64(708)

In [15]:
df['horsepower'] = df['horsepower'].fillna(149.0)

In [16]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0       149.0     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [17]:
df['horsepower'].isnull().sum()

np.int64(0)

In [19]:
# Recalculating median value:
df['horsepower'].median()

np.float64(149.0)

### Q7. Sum of weights

In [25]:
df_asian = df[
    df['origin'] == 'Asia'
]

X = df_asian[['vehicle_weight', 'model_year']].iloc[0:7].to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [45]:
XT = X.T
XTX = (XT).dot(X) # gets a 2x2 matrix now.
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [43]:
import numpy as np
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [44]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [46]:
# XTX_inv.shape
# XTX_inv - 2x2

# X.shape
# X       - 7x2

# y.shape
# y       - 7x1

(2, 7)

In [47]:
w = XTX_inv.dot(XT).dot(y)
w

array([0.01386421, 0.5049067 ])

In [48]:
w.sum()

np.float64(0.5187709081074016)

In [ ]:
# Answer: 0.5187709081074016